# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.pdsm
canonical: https://interop.esante.gouv.fr/ig/fhir/pdsm
name: PDSm
title: Partage de Documents de Santé en mobilité (PDSm)
publisher:
    name: ANS
    url: https://esante.gouv.fr
status: active
version: 3.1.1
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    ihe.iti.mhd: 4.2.0
    ans.fhir.fr.annuaire: 1.1.0
    hl7.fhir.fr.core: 2.1.0
    ans.fr.terminologies: latest

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Spécifications fonctionnelles - vue d'ensemble
        sf_ajout.md:
            title: Ajout d'un lot de documents
        sf_maj.md:
            title: Mise à jour de documents
        sf_recherche.md:
            title: Recherche de documents
        sf_consultation.md:
            title: Consultation de documents
    construction_des_flux.md:
        title: Spécifications techniques - vue d'ensemble
        st_ajout.md:
            title: Ajout d'un lot de documents (ITI-65)
        st_maj.md:
            title: Mise à jour de documents
        st_recherche_lot.md:
            title: Recherche de lot de soumission (ITI-66)
        st_recherche_fiche.md:
            title: Recherche de fiche (ITI-67)
        st_consultation.md:
            title: Consultation de documents (ITI-68)
        st_ajout_simplifie.md:
            title: Ajout simplifié d'un document (ITI-105)            
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        equivalences.md:
            title: Equivalences
        downloads.md:
            title: Téléchargements et usages
    changes.md:
        title: Historique des changements

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle:
        Vue d'ensemble: specifications_fonctionnelles.html
        Ajout d'un lot de documents: sf_ajout.html
        Mise à jour de documents: sf_maj.html
        Recherche de documents: sf_recherche.html
        Consultation de documents: sf_consultation.html
    Volume 2 - Détail des transactions:
        Vue d'ensemble: construction_des_flux.html
        Ajout d'un lot de soumission (ITI-65): st_ajout.html 
        Mise à jour de documents: st_maj.html
        Recherche de lot de soumission (ITI-66): st_recherche_lot.html
        Recherche de fiche (ITI-67): st_recherche_fiche.html
        Consultation de documents (ITI-68): st_consultation.html
        Ajout simplifié d'un document (ITI-105): st_ajout_simplifie.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Equivalences: equivalences.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: changes.html
